// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_BLScreen_screen_init(void)
{
    ui_BLScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_FLLabel1 = lv_label_create(ui_BLScreen);
    lv_obj_set_width(ui_FLLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLLabel1, 10);
    lv_obj_set_y(ui_FLLabel1, 10);
    lv_label_set_text(ui_FLLabel1, "Back Left");
    lv_obj_set_style_text_font(ui_FLLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Side1 = lv_label_create(ui_BLScreen);
    lv_obj_set_width(ui_Side1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Side1, 10);
    lv_obj_set_y(ui_Side1, 50);
    lv_label_set_text(ui_Side1, "Side");
    lv_obj_set_style_text_font(ui_Side1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top1 = lv_label_create(ui_BLScreen);
    lv_obj_set_width(ui_Top1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Top1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Top1, 10);
    lv_obj_set_y(ui_Top1, 140);
    lv_label_set_text(ui_Top1, "Top");
    lv_obj_set_style_text_font(ui_Top1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bottom1 = lv_label_create(ui_BLScreen);
    lv_obj_set_width(ui_Bottom1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bottom1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bottom1, 10);
    lv_obj_set_y(ui_Bottom1, 230);
    lv_label_set_text(ui_Bottom1, "Bottom");
    lv_obj_set_style_text_font(ui_Bottom1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flSideSlider1 = lv_slider_create(ui_BLScreen);
    lv_slider_set_range(ui_flSideSlider1, -25, 230);
    lv_slider_set_value(ui_flSideSlider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flSideSlider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flSideSlider1, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_flSideSlider1, 400);
    lv_obj_set_height(ui_flSideSlider1, 30);
    lv_obj_set_x(ui_flSideSlider1, 0);
    lv_obj_set_y(ui_flSideSlider1, -60);
    lv_obj_set_align(ui_flSideSlider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flSideSlider1, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flSideSlider1, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flSideSlider1, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flSideSlider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flSideSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flSideSlider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flSideSlider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_flTopSlider1 = lv_slider_create(ui_BLScreen);
    lv_slider_set_range(ui_flTopSlider1, -25, 230);
    lv_slider_set_value(ui_flTopSlider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flTopSlider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flTopSlider1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_flTopSlider1, 400);
    lv_obj_set_height(ui_flTopSlider1, 30);
    lv_obj_set_x(ui_flTopSlider1, 0);
    lv_obj_set_y(ui_flTopSlider1, 30);
    lv_obj_set_align(ui_flTopSlider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flTopSlider1, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flTopSlider1, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flTopSlider1, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flTopSlider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flTopSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flTopSlider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flTopSlider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_flBotSlider1 = lv_slider_create(ui_BLScreen);
    lv_slider_set_range(ui_flBotSlider1, -25, 230);
    lv_slider_set_value(ui_flBotSlider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flBotSlider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flBotSlider1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_flBotSlider1, 400);
    lv_obj_set_height(ui_flBotSlider1, 30);
    lv_obj_set_x(ui_flBotSlider1, 0);
    lv_obj_set_y(ui_flBotSlider1, 120);
    lv_obj_set_align(ui_flBotSlider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flBotSlider1, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flBotSlider1, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flBotSlider1, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flBotSlider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flBotSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flBotSlider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flBotSlider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_backButton1 = lv_btn_create(ui_BLScreen);
    lv_obj_set_width(ui_backButton1, 100);
    lv_obj_set_height(ui_backButton1, 50);
    lv_obj_set_x(ui_backButton1, 0);
    lv_obj_set_y(ui_backButton1, -10);
    lv_obj_set_align(ui_backButton1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_backButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton1, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_backButton1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "Back");

    lv_obj_add_event_cb(ui_flSideSlider1, ui_event_flSideSlider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flTopSlider1, ui_event_flTopSlider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flBotSlider1, ui_event_flBotSlider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton1, ui_event_backButton1, LV_EVENT_ALL, NULL);

}
