// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_BRScreen_screen_init(void)
{
    ui_BRScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BRScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_FLLabel3 = lv_label_create(ui_BRScreen);
    lv_obj_set_width(ui_FLLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLLabel3, 10);
    lv_obj_set_y(ui_FLLabel3, 10);
    lv_label_set_text(ui_FLLabel3, "Back Right");
    lv_obj_set_style_text_font(ui_FLLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Side3 = lv_label_create(ui_BRScreen);
    lv_obj_set_width(ui_Side3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Side3, 10);
    lv_obj_set_y(ui_Side3, 50);
    lv_label_set_text(ui_Side3, "Side");
    lv_obj_set_style_text_font(ui_Side3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top3 = lv_label_create(ui_BRScreen);
    lv_obj_set_width(ui_Top3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Top3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Top3, 10);
    lv_obj_set_y(ui_Top3, 140);
    lv_label_set_text(ui_Top3, "Top");
    lv_obj_set_style_text_font(ui_Top3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bottom3 = lv_label_create(ui_BRScreen);
    lv_obj_set_width(ui_Bottom3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bottom3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bottom3, 10);
    lv_obj_set_y(ui_Bottom3, 230);
    lv_label_set_text(ui_Bottom3, "Bottom");
    lv_obj_set_style_text_font(ui_Bottom3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flSideSlider3 = lv_slider_create(ui_BRScreen);
    lv_slider_set_range(ui_flSideSlider3, -25, 230);
    lv_slider_set_value(ui_flSideSlider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flSideSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flSideSlider3, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_flSideSlider3, 400);
    lv_obj_set_height(ui_flSideSlider3, 30);
    lv_obj_set_x(ui_flSideSlider3, 0);
    lv_obj_set_y(ui_flSideSlider3, -60);
    lv_obj_set_align(ui_flSideSlider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flSideSlider3, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flSideSlider3, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flSideSlider3, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flSideSlider3, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flSideSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flSideSlider3, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flSideSlider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_flTopSlider3 = lv_slider_create(ui_BRScreen);
    lv_slider_set_range(ui_flTopSlider3, -25, 230);
    lv_slider_set_value(ui_flTopSlider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flTopSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flTopSlider3, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_flTopSlider3, 400);
    lv_obj_set_height(ui_flTopSlider3, 30);
    lv_obj_set_x(ui_flTopSlider3, 0);
    lv_obj_set_y(ui_flTopSlider3, 30);
    lv_obj_set_align(ui_flTopSlider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flTopSlider3, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flTopSlider3, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flTopSlider3, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flTopSlider3, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flTopSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flTopSlider3, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flTopSlider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_flBotSlider3 = lv_slider_create(ui_BRScreen);
    lv_slider_set_range(ui_flBotSlider3, -25, 230);
    lv_slider_set_value(ui_flBotSlider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flBotSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flBotSlider3, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_flBotSlider3, 400);
    lv_obj_set_height(ui_flBotSlider3, 30);
    lv_obj_set_x(ui_flBotSlider3, 0);
    lv_obj_set_y(ui_flBotSlider3, 120);
    lv_obj_set_align(ui_flBotSlider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flBotSlider3, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flBotSlider3, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flBotSlider3, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flBotSlider3, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flBotSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flBotSlider3, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flBotSlider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_backButton2 = lv_btn_create(ui_BRScreen);
    lv_obj_set_width(ui_backButton2, 100);
    lv_obj_set_height(ui_backButton2, 50);
    lv_obj_set_x(ui_backButton2, 0);
    lv_obj_set_y(ui_backButton2, -10);
    lv_obj_set_align(ui_backButton2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_backButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton2, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_backButton2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "Back");

    lv_obj_add_event_cb(ui_flSideSlider3, ui_event_flSideSlider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flTopSlider3, ui_event_flTopSlider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flBotSlider3, ui_event_flBotSlider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton2, ui_event_backButton2, LV_EVENT_ALL, NULL);

}
