// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void sendHump(lv_event_t * e);
void getPositionLegs(lv_event_t * e);
void sendSit1(lv_event_t * e);
void standSend1(lv_event_t * e);
void crabSend1(lv_event_t * e);
void resetPositionDog(lv_event_t * e);
void flSideChangeVal(lv_event_t * e);
void flTopChangeVal(lv_event_t * e);
void flBotChangeVal(lv_event_t * e);
void frSideChangeVal(lv_event_t * e);
void frTopChangeVal(lv_event_t * e);
void frBotChangeVal(lv_event_t * e);
void blSideChangeVal(lv_event_t * e);
void blTopChangeVal(lv_event_t * e);
void blBotChangeVal(lv_event_t * e);
void brSideChangeVal(lv_event_t * e);
void brTopChangeVal(lv_event_t * e);
void brBotChangeVal(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
