// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_FLScreen_screen_init(void)
{
    ui_FLScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FLScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_FLLabel5 = lv_label_create(ui_FLScreen);
    lv_obj_set_width(ui_FLLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLLabel5, 10);
    lv_obj_set_y(ui_FLLabel5, 10);
    lv_label_set_text(ui_FLLabel5, "Front Left");
    lv_obj_set_style_text_font(ui_FLLabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Side = lv_label_create(ui_FLScreen);
    lv_obj_set_width(ui_Side, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Side, 10);
    lv_obj_set_y(ui_Side, 50);
    lv_label_set_text(ui_Side, "Side");
    lv_obj_set_style_text_font(ui_Side, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top = lv_label_create(ui_FLScreen);
    lv_obj_set_width(ui_Top, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Top, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Top, 10);
    lv_obj_set_y(ui_Top, 140);
    lv_label_set_text(ui_Top, "Top");
    lv_obj_set_style_text_font(ui_Top, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bottom = lv_label_create(ui_FLScreen);
    lv_obj_set_width(ui_Bottom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bottom, 10);
    lv_obj_set_y(ui_Bottom, 230);
    lv_label_set_text(ui_Bottom, "Bottom");
    lv_obj_set_style_text_font(ui_Bottom, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flSideSlider = lv_slider_create(ui_FLScreen);
    lv_slider_set_range(ui_flSideSlider, -25, 230);
    lv_slider_set_value(ui_flSideSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flSideSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flSideSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_flSideSlider, 400);
    lv_obj_set_height(ui_flSideSlider, 30);
    lv_obj_set_x(ui_flSideSlider, 0);
    lv_obj_set_y(ui_flSideSlider, -60);
    lv_obj_set_align(ui_flSideSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flSideSlider, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flSideSlider, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flSideSlider, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flSideSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flSideSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flSideSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flSideSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flSideSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_flTopSlider = lv_slider_create(ui_FLScreen);
    lv_slider_set_range(ui_flTopSlider, -25, 230);
    lv_slider_set_value(ui_flTopSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flTopSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flTopSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_flTopSlider, 400);
    lv_obj_set_height(ui_flTopSlider, 30);
    lv_obj_set_x(ui_flTopSlider, 0);
    lv_obj_set_y(ui_flTopSlider, 30);
    lv_obj_set_align(ui_flTopSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flTopSlider, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flTopSlider, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flTopSlider, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flTopSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flTopSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flTopSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flTopSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flTopSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_flBotSlider = lv_slider_create(ui_FLScreen);
    lv_slider_set_range(ui_flBotSlider, -25, 230);
    lv_slider_set_value(ui_flBotSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_flBotSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_flBotSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_flBotSlider, 400);
    lv_obj_set_height(ui_flBotSlider, 30);
    lv_obj_set_x(ui_flBotSlider, 0);
    lv_obj_set_y(ui_flBotSlider, 120);
    lv_obj_set_align(ui_flBotSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_flBotSlider, lv_color_hex(0x390000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flBotSlider, lv_color_hex(0x7E0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_flBotSlider, lv_color_hex(0x7E0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_flBotSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_flBotSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_flBotSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_flBotSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_flBotSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_backButton = lv_btn_create(ui_FLScreen);
    lv_obj_set_width(ui_backButton, 100);
    lv_obj_set_height(ui_backButton, 50);
    lv_obj_set_x(ui_backButton, 0);
    lv_obj_set_y(ui_backButton, -10);
    lv_obj_set_align(ui_backButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_backButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label18, "Back");

    lv_obj_add_event_cb(ui_flSideSlider, ui_event_flSideSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flTopSlider, ui_event_flTopSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_flBotSlider, ui_event_flBotSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);

}
