// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
// #include "IMG_LogoWufar.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    create_battery_status(ui_HomeScreen);
    
    ui_LimbControl1 = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_LimbControl1, 180);
    lv_obj_set_height(ui_LimbControl1, 150);
    lv_obj_set_x(ui_LimbControl1, -100);
    lv_obj_set_y(ui_LimbControl1, -80);
    lv_obj_set_align(ui_LimbControl1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LimbControl1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LimbControl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LimbControl1, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LimbControl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LimbControl1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LimbControl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_LimbControl1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Limb\nControl");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Walk = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_Walk, 180);
    lv_obj_set_height(ui_Walk, 150);
    lv_obj_set_x(ui_Walk, 100);
    lv_obj_set_y(ui_Walk, -80);
    lv_obj_set_align(ui_Walk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Walk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Walk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Walk, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Walk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Walk, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Walk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lable2 = lv_label_create(ui_Walk);
    lv_obj_set_width(ui_Lable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lable2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lable2, "Walk");
    lv_obj_set_style_text_color(ui_Lable2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lable2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Lable2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lable2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sitDown = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_sitDown, 150);
    lv_obj_set_height(ui_sitDown, 150);
    lv_obj_set_x(ui_sitDown, -160);
    lv_obj_set_y(ui_sitDown, 80);
    lv_obj_set_align(ui_sitDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sitDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sitDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sitDown, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sitDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_sitDown, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sitDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lable3 = lv_label_create(ui_sitDown);
    lv_obj_set_width(ui_Lable3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lable3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lable3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lable3, "Sit");
    lv_obj_set_style_text_color(ui_Lable3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lable3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Lable3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lable3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_standup = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_standup, 150);
    lv_obj_set_height(ui_standup, 150);
    lv_obj_set_x(ui_standup, 160);
    lv_obj_set_y(ui_standup, 80);
    lv_obj_set_align(ui_standup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_standup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_standup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_standup, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_standup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_standup, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_standup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lable4 = lv_label_create(ui_standup);
    lv_obj_set_width(ui_Lable4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lable4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Lable4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lable4, "Stand");
    lv_obj_set_style_text_color(ui_Lable4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lable4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Lable4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lable4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // // Create an image object
    // lv_obj_t *img = lv_img_create(LogoWufarCut_smol_map);

    // // Set the image source
    // lv_img_set_src(img, &LogoWufarCut_smol_map);

    // // Resize the image
    // lv_obj_set_width(img, 150);  // Set the width to 100 pixels
    // lv_obj_set_height(img, 150); // Set the height to 100 pixels

    // // Align the image (optional)
    // lv_obj_align(img, LV_ALIGN_CENTER, 80, 0);

    ui_HumpBut = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_HumpBut, 150);
    lv_obj_set_height(ui_HumpBut, 150);
    lv_obj_set_x(ui_HumpBut, 0);
    lv_obj_set_y(ui_HumpBut, 80);
    lv_obj_set_align(ui_HumpBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumpBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HumpBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumpBut, lv_color_hex(0x7E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumpBut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_HumpBut, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumpBut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumpLable = lv_label_create(ui_HumpBut);
    lv_obj_set_width(ui_HumpLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumpLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumpLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumpLable, "Hump");
    lv_obj_set_style_text_color(ui_HumpLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumpLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HumpLable, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumpLable, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HumpBut, ui_event_Hump, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LimbControl1, ui_event_LimbControl1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Walk, ui_event_Walk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sitDown, ui_event_Placeholder2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_standup, ui_event_Placeholder1, LV_EVENT_ALL, NULL);
    uic_HomeScreen = ui_HomeScreen;
    uic_LimbControl = ui_LimbControl1;
    uic_LimbControl = ui_Walk;
    uic_LimbControl = ui_sitDown;
    uic_LimbControl = ui_standup;

}
